apiVersion: v1
kind: Service
metadata:
  labels:
    name: docker-hello-world
    role: web
  name: docker-hello-world
  namespace: docker-hello-world
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: docker-hello-world
    role: web
  type: LoadBalancer
