apiVersion: v1
kind: Pod
metadata:
  name: docker-hello-world
  namespace: docker-hello-world
  labels:
    name: docker-hello-world
    role: web
spec:
  containers:
    - image: koudaiii/hello-world:latest
      name: docker-hello-world
      ports:
        - containerPort: 8080
      env:
        - name: MESSAGE
          value: Hello Wantedly
