apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
    role: web
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: hello-world
      labels:
        name: hello-world
        role: web
    spec:
      containers:
      - image: koudaiii/hello-world:latest
        name: hello-world
        ports:
          - containerPort: 8080
        env:
          - name: MESSAGE
            value: Hello Wantedly
