apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello-world
    role: web
  name: hello-world
spec:
  ports:
  - name: hello-world
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: hello-world
    role: web
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
    role: web
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: hello-world
      labels:
        name: hello-world
        role: web
    spec:
      containers:
      - image: koudaiii/hello-world:latest
        name: hello-world
        ports:
          - containerPort: 8080
            name: hello-world
        env:
          - name: MESSAGE
            value: Hello Wantedly
